name: CI
on:
  push:
    branches:
      - master
jobs:
  run_test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Tests
        run: python manage.py test
